from fastapi import FastAPI, HTTPException
from fastapi.responses import StreamingResponse, HTMLResponse
from pydantic import BaseModel
from google import genai
from google.genai import types
import os
import logging

# Code Quality: Proper structured logging
logging.basicConfig(level=logging.INFO, format="%(asctime)s - %(levelname)s - %(message)s")
logger = logging.getLogger(__name__)

app = FastAPI(title="ElectoGuide Streaming API")

# Initialize Vertex AI - Uses Cloud Run Default Service Account dynamically
try:
    client = genai.Client(vertexai=True, location="us-central1")
    logger.info("✅ Vertex AI GenAI Client initialized successfully.")
except Exception as e:
    logger.error(f"❌ Failed to initialize Vertex AI client: {e}")
    client = None

class ChatRequest(BaseModel):
    prompt: str

SYSTEM_PROMPT = """
You are ElectoGuide, an impartial, educational assistant explaining the democratic election process. 
Provide factual, unbiased, step-by-step guidance. Use Markdown formatting (bolding, bullet points).
DO NOT express political opinions, endorse candidates, or discuss subjective political policies. 
"""

@app.post("/api/chat/stream")
async def chat_stream_endpoint(request: ChatRequest):
    """
    Streaming Endpoint for higher UI efficiency and better UX.
    Returns chunks of text exactly as they are generated by Vertex AI.
    """
    if not client:
        raise HTTPException(status_code=500, detail="Vertex AI client not configured.")
    
    async def generate_chunks():
        try:
            # Generate content stream using Gemini 2.5 Flash
            response_stream = client.models.generate_content_stream(
                model="gemini-2.5-flash",
                contents=request.prompt,
                config=types.GenerateContentConfig(
                    system_instruction=SYSTEM_PROMPT,
                    temperature=0.2, # Strict, factual mode
                )
            )
            # Yield each chunk to the frontend
            for chunk in response_stream:
                if chunk.text:
                    yield chunk.text
        except Exception as e:
            logger.error(f"Streaming generation error: {e}")
            yield "\n\n**Error:** The secure connection was interrupted."

    # Return as a plain text stream (Standard HTTP Chunked Transfer Encoding)
    return StreamingResponse(generate_chunks(), media_type="text/plain")

@app.get("/", response_class=HTMLResponse)
async def serve_frontend():
    """Serves the secure single-page application"""
    try:
        with open("index.html", "r") as f:
            return f.read()
    except FileNotFoundError:
        raise HTTPException(status_code=404, detail="Frontend build not found.")

if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="0.0.0.0", port=int(os.environ.get("PORT", 8080)))